        Thread.Sleep(2000);
        Console.ForegroundColor = ConsoleColor.Red;
        Console.BackgroundColor = ConsoleColor.Yellow;
        Console.WriteLine("PROTOCOLOS DE CONTENÇÃO ATIVADOS");
        Thread.Sleep(2000);
        Console.WriteLine("ISOLANDO ÁREA AFETADA...");
        Thread.Sleep(2000);
        Console.WriteLine("DESCONTAMINAÇÃO EM ANDAMENTO...");
        Thread.Sleep(2000);
        Console.WriteLine("ATIVAÇÃO DE RESPOSTA IMUNOLÓGICA ASSISTIDA...");
        Thread.Sleep(2000);
        Console.WriteLine();
        Console.ForegroundColor = ConsoleColor.Green;
        Console.BackgroundColor = ConsoleColor.White;
        Console.WriteLine("AMEAÇA NEUTRALIZADA! DESATIVANDO QUARENTENA...");
        Console.ForegroundColor = ConsoleColor.White;
        Console.BackgroundColor = ConsoleColor.Black;
        Console.WriteLine();
        Console.WriteLine("ENTER PARA CONTINUAR");
        Console.ReadKey();